build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:latest
  armv7: ghcr.io/home-assistant/armv7-base-debian:latest
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
labels:
  io.hass.name: "RustBerry PoE Monitor"
  io.hass.description: "Monitor and control Raspberry Pi PoE HAT (B) with OLED display"
  io.hass.type: addon
